// packages/dialog/react/lib/DialogClose.tsx
import {type DialogModel} from '@ally-ui/core-dialog';
import {useRunOnce} from '@ally-ui/react';
import {PropsWithChildren, useCallback} from 'react';

export interface DialogCloseProps extends PropsWithChildren {
	model: DialogModel;
}

export default function DialogClose({model, children}: DialogCloseProps) {
	const id = useRunOnce(() => model.init('close'));

	const ref = useCallback(
		(node: HTMLElement | null) => {
			if (node === null) {
				model.unbindNode(id);
			} else {
				model.bindNode(id, node);
			}
		},
		[model],
	);

	const handleClick = useCallback(() => {
		model.setState((prevState) => ({...prevState, open: false}));
	}, [model]);

	return (
		<button
			ref={ref}
			{...model.submodelDOMAttributes(id)}
			onClick={handleClick}
		>
			{children}
		</button>
	);
}

// packages/svelte-dialog/lib/DialogClose.svelte
<script lang="ts">
	import type {DialogModel} from '@ally-ui/core-dialog';
	import type {Readable} from 'svelte/store';

	export let model: Readable<DialogModel>;
	const id = $model.init('close');

	let node: HTMLElement | undefined;
	$: bindNode(node);
	function bindNode(node?: HTMLElement) {
		if (node === undefined) {
			$model.unbindNode(id);
		} else {
			$model.bindNode(id, node);
		}
	}
</script>

<button
	bind:this={node}
	{...$model.submodelDOMAttributes(id)}
	on:click={() => $model.setState((prevState) => ({...prevState, open: false}))}
>
	<slot />
</button>
