// packages/react-dialog/lib/DialogTitle.tsx
import {type DialogModel} from '@ally-ui/core-dialog';
import {useRunOnce} from '@ally-ui/react-utils';
import {PropsWithChildren, useCallback} from 'react';

export interface DialogTitleProps extends PropsWithChildren {
	model: DialogModel;
}

export default function DialogTitle({model, children}: DialogTitleProps) {
	const id = useRunOnce(() => model.init('title'));

	const ref = useCallback(
		(node: HTMLElement | null) => {
			if (node === null) {
				model.unbindNode(id);
			} else {
				model.bindNode(id, node);
			}
		},
		[model],
	);

	return (
		<h1 ref={ref} {...model.submodelDOMAttributes(id)}>
			{children}
		</h1>
	);
}

// packages/svelte-dialog/lib/DialogTitle.svelte
<script lang="ts">
	import type {DialogModel} from '@ally-ui/core-dialog';
	import type {Readable} from 'svelte/store';

	export let model: Readable<DialogModel>;
	const id = $model.init('title');

	let node: HTMLElement | undefined;
	$: bindNode(node);
	function bindNode(node?: HTMLElement) {
		if (node === undefined) {
			$model.unbindNode(id);
		} else {
			$model.bindNode(id, node);
		}
	}
</script>

<h1 bind:this={node} {...$model.submodelDOMAttributes(id)}>
	<slot />
</h1>
