// packages/dialog/svelte/lib/DialogRoot.svelte
<script lang="ts">
	import {DialogRootModel} from '@ally-ui/core-dialog';
	import {bindStore, createSyncedOption} from '@ally-ui/svelte';
	import {derived, writable} from 'svelte/store';
	import {setDialogRootModel, setDialogRootState} from './context';

	interface $$Props {
		open?: boolean;
		initialOpen?: boolean;
	}
	export let open: boolean | undefined = undefined;
	const openStore = writable(open);
	const watchOpen = bindStore(openStore, (o) => (open = o));
	$: watchOpen(open);

	export let initialOpen: boolean | undefined = undefined;

	// TODO #19 Generate SSR-safe IDs.
	const id = '0';
	const rootModel = new DialogRootModel(id, {initialOpen});
	const rootState = writable(rootModel.initialState);
	rootModel.setStateOptions((prevOptions) => ({
		...prevOptions,
		requestStateUpdate: (updater) => {
			if (updater instanceof Function) {
				rootState.update(updater);
			} else {
				rootState.set(updater);
			}
		},
	}));
	createSyncedOption({
		option: openStore,
		onOptionChange: ($open) =>
			rootState.update((prevState) => ({...prevState, open: $open})),
		internal: derived(rootState, ($state) => $state.open),
	});
	$: rootModel.setState($rootState);

	setDialogRootModel(rootModel);
	setDialogRootState(rootState);
</script>

<slot />

// packages/dialog/vue/lib/DialogRoot.vue
<script setup lang="ts">
import {DialogRootModel} from '@ally-ui/core-dialog';
import {useSyncedOption} from '@ally-ui/vue';
import {computed, provide, ref, watchEffect} from 'vue';
import {DIALOG_ROOT_MODEL, DIALOG_ROOT_STATE} from './context';

export type DialogRootProps = {
	open?: boolean;
	initialOpen?: boolean;
};

const props = withDefaults(defineProps<DialogRootProps>(), {
	open: undefined,
	initialOpen: undefined,
});
const emit = defineEmits<{
	(ev: 'update:open', open: boolean): void;
}>();

// TODO #19 Generate SSR-safe IDs.
const id = '0';
const rootModel = new DialogRootModel(id, {initialOpen: props.initialOpen});
const rootState = ref(rootModel.initialState);
rootModel.setStateOptions((prevOptions) => ({
	...prevOptions,
	requestStateUpdate: (updater) => {
		if (updater instanceof Function) {
			rootState.value = updater(rootState.value);
		} else {
			rootState.value = updater;
		}
	},
}));
useSyncedOption({
	option: computed(() => props.open),
	onOptionChange: (open) => (rootState.value = {...rootState.value, open}),
	internal: computed(() => rootState.value.open),
	onInternalChange: (open) => emit('update:open', open),
});
watchEffect(function onStateUpdate() {
	rootModel.setState(rootState.value);
});

provide(DIALOG_ROOT_MODEL, rootModel);
provide(DIALOG_ROOT_STATE, rootState);
</script>

<template>
	<slot />
</template>
