// packages/dialog/svelte/lib/DialogDescription.svelte
<script lang="ts">
	import {DialogDescriptionModel} from '@ally-ui/core-dialog';
	import {createEventForwarder} from '@ally-ui/svelte';
	import {get_current_component, onMount} from 'svelte/internal';
	import {getDialogRootModel} from './context';

	type $$Props = svelteHTML.IntrinsicElements['p'] & {
		node?: HTMLParagraphElement | undefined | null;
	};

	const rootModel = getDialogRootModel();
	if (rootModel === undefined) {
		throw new Error(
			'<Dialog.Description/> must be a child of `<Dialog.Root/>`',
		);
	}
	const component = rootModel.registerComponent(
		new DialogDescriptionModel(rootModel, {}),
	);
	const id = component.getId();

	onMount(() => {
		rootModel.mountComponent(id);
		return () => {
			rootModel.unmountComponent(id);
		};
	});

	export let node: HTMLElement | null | undefined = null;
	$: bindNode(node);
	function bindNode(node?: HTMLElement | null) {
		if (node == null) {
			rootModel.unbindComponent(id);
		} else {
			rootModel.bindComponent(id, node);
		}
	}

	const eventForwarder = createEventForwarder(get_current_component());
</script>

<p
	bind:this={node}
	{...component.getAttributes()}
	{...$$restProps}
	use:eventForwarder
>
	<slot />
</p>

// packages/dialog/vue/lib/DialogDescription.vue
<script setup lang="ts">
import {DialogDescriptionModel} from '@ally-ui/core-dialog';
import {inject, onMounted, onUnmounted, ref, watchEffect} from 'vue';
import {DIALOG_ROOT_MODEL} from './context';

const rootModel = inject(DIALOG_ROOT_MODEL);
if (rootModel === undefined) {
	throw new Error('<Dialog.Description/> must be a child of `<Dialog.Root/>`');
}
const component = rootModel.registerComponent(
	new DialogDescriptionModel(rootModel, {}),
);
const id = component.getId();

onMounted(() => rootModel.mountComponent(id));
onUnmounted(() => rootModel.unmountComponent(id));

const node = ref<HTMLElement | null>(null);
watchEffect(() => {
	if (node.value === null) {
		rootModel.unbindComponent(id);
	} else {
		rootModel.bindComponent(id, node.value);
	}
});
</script>

<template>
	<p ref="node" v-bind="{...component.getAttributes(), ...$attrs}">
		<slot />
	</p>
</template>
