// packages/dialog/svelte/lib/DialogContent.svelte
<script lang="ts" context="module">
	type DialogContentProps<TAsChild extends true | undefined> =
		DialogContentModelProps &
			svelteHTML.IntrinsicElements['div'] & {
				node?: HTMLDivElement | undefined | null;
				asChild?: TAsChild;
			};
	type DialogContentSlots<TAsChild extends true | undefined> = {
		default: DefaultSlot<
			TAsChild,
			DialogContentModelAttributes,
			svelteHTML.IntrinsicElements['div'],
			RefAction
		>;
	};
</script>

<script lang="ts">
	import {
		DialogContentModel,
		type DialogContentModelAttributes,
		type DialogContentModelEvents,
		type DialogContentModelProps,
	} from '@ally-ui/core-dialog';
	import {
		createEventForwarder,
		createNativeEventDispatcher,
		createRefAction,
		mergeSvelteProps,
		svelteProps,
		type DefaultSlot,
		type RefAction,
		type SvelteEventHandlers,
	} from '@ally-ui/svelte';
	import {onMount} from 'svelte/internal';
	import {readable} from 'svelte/store';
	import {
		getDialogPortalForceMount,
		getDialogRootModel,
		getDialogRootState,
	} from './context';

	type TAsChild = $$Generic<true | undefined>;
	type $$Props = DialogContentProps<TAsChild>;
	type $$Slots = DialogContentSlots<TAsChild>;
	type $$Events = SvelteEventHandlers<DialogContentModelEvents>;

	const dispatch = createNativeEventDispatcher<$$Events>();

	const rootModel = getDialogRootModel();
	if (rootModel == null) {
		throw new Error('<Dialog.Content/> must be a child of `<Dialog.Root/>`');
	}
	export let forceMount: boolean | undefined = undefined;
	export let allowPinchZoom: boolean | undefined = undefined;
	const component = new DialogContentModel(
		{
			forceMount: forceMount ?? getDialogPortalForceMount(),
			allowPinchZoom,
		},
		{
			openAutoFocus: (ev) => dispatch('openAutoFocus', ev),
			closeAutoFocus: (ev) => dispatch('closeAutoFocus', ev),
			escapeKeyDown: (ev) => dispatch('escapeKeyDown', ev),
			interactOutside: (ev) => dispatch('interactOutside', ev),
		},
		rootModel,
	);

	const state = component.state.initialValue;
	// Note that we do not need to sync options for event handlers because Svelte
	// does not use handlers but emits events instead.

	const rootState = getDialogRootState() ?? readable(rootModel.state.value);
	$: derivedState = component.derived(state, $rootState);

	onMount(() => {
		component.mount();
		return () => {
			component.unmount();
			component.unregister();
		};
	});

	export let node: HTMLElement | null | undefined = null;
	$: bindNode(node);
	function bindNode(node?: HTMLElement | null) {
		if (node == null) {
			component.unbind();
		} else {
			component.bind(node);
		}
	}

	const ref = createRefAction((n) => (node = n));

	export let asChild: TAsChild = undefined as TAsChild;

	$: slotProps = {
		props: (userProps: svelteHTML.IntrinsicElements['div']) =>
			mergeSvelteProps(
				svelteProps(component.attributes(state, $rootState)),
				$$restProps,
				userProps,
			),
		ref,
	} as any; // Workaround to allow conditional slot type.

	const eventForwarder = createEventForwarder([
		'openAutoFocus',
		'closeAutoFocus',
		'escapeKeyDown',
		'interactOutside',
	]);
</script>

{#if derivedState.show}
	{#if asChild}
		<slot {...slotProps} />
	{:else}
		<div
			bind:this={node}
			{...mergeSvelteProps(
				svelteProps(component.attributes(state, $rootState)),
				$$restProps,
			)}
			use:eventForwarder
		>
			<slot {...slotProps} />
		</div>
	{/if}
{/if}

// packages/dialog/vue/lib/DialogContent.vue
<script setup lang="ts">
import {DialogContentModel} from '@ally-ui/core-dialog';
import {computed, inject, onMounted, onUnmounted, ref, watchEffect} from 'vue';
import {
	DIALOG_PORTAL_FORCE_MOUNT,
	DIALOG_ROOT_MODEL,
	DIALOG_ROOT_STATE,
} from './context';
import {mergeVueProps} from '@ally-ui/vue';

/**
 * @type {import('@ally-ui/core-dialog').DialogContentModelProps}
 */
export type DialogContentProps = {
	setRef?: (node: HTMLDivElement | null) => void;
	asChild?: true | undefined;
	forceMount?: boolean | undefined;
	allowPinchZoom?: boolean | undefined;
};
/**
 * @type {import('@ally-ui/core-dialog').DialogContentModelEvents}
 */
export type DialogContentEvents = {
	(type: 'openAutoFocus', ev: Event): void;
	(type: 'closeAutoFocus', ev: Event): void;
	(type: 'escapeKeyDown', ev: KeyboardEvent): void;
	(type: 'interactOutside', ev: MouseEvent | TouchEvent): void;
};
const props = withDefaults(defineProps<DialogContentProps>(), {
	asChild: undefined,
	forceMount: undefined,
	allowPinchZoom: undefined,
});
const emit = defineEmits<DialogContentEvents>();

const rootModel = inject(DIALOG_ROOT_MODEL);
if (rootModel == null) {
	throw new Error('<Dialog.Content/> must be a child of `<Dialog.Root/>`');
}
const portalForceMount = inject(DIALOG_PORTAL_FORCE_MOUNT);
const component = new DialogContentModel(
	{
		forceMount: props.forceMount ?? portalForceMount,
		allowPinchZoom: props.allowPinchZoom,
	},
	{
		openAutoFocus: (ev) => emit('openAutoFocus', ev),
		closeAutoFocus: (ev) => emit('closeAutoFocus', ev),
		escapeKeyDown: (ev) => emit('escapeKeyDown', ev),
		interactOutside: (ev) => emit('interactOutside', ev),
	},
	rootModel,
);

const state = ref(component.state.initialValue);
// Note that we do not need to sync options for event handlers because Vue does
// not use handlers but emits events instead.

const rootState = inject(DIALOG_ROOT_STATE) ?? ref(rootModel.state.value);
const derivedState = computed(() =>
	component.derived(state.value, rootState.value),
);

onMounted(() => component.mount());
onUnmounted(() => {
	component.unmount();
	component.unregister();
});

const node = ref<HTMLDivElement | null>(null);
const setRef = (nodeValue: HTMLDivElement | null) => {
	node.value = nodeValue;
};
watchEffect(() => {
	props.setRef?.(node.value);
	if (node.value == null) {
		component.unbind();
	} else {
		component.bind(node.value);
	}
});
</script>

<template>
	<template v-if="derivedState.show">
		<slot
			v-if="props.asChild"
			v-bind="{
				...mergeVueProps(component.attributes(state, rootState), $attrs),
				ref: setRef,
			}"
		/>
		<div
			v-else
			ref="node"
			v-bind="mergeVueProps(component.attributes(state, rootState), $attrs)"
		>
			<slot />
		</div>
	</template>
</template>
