// packages/dialog/vue/lib/DialogTrigger.vue
<script setup lang="ts">
import type {DialogModel} from '@ally-ui/core-dialog';
import {
	defineProps,
	inject,
	onMounted,
	onUnmounted,
	ref,
	watchEffect,
} from 'vue';
import {MODEL_KEY, STATE_KEY} from './context';

const props = withDefaults(
	defineProps<{
		model?: DialogModel;
	}>(),
	{},
);

const resolvedModel = props.model ?? inject(MODEL_KEY);
if (resolvedModel === undefined) {
	throw new Error(
		'<Dialog.Trigger/> must have a `model` prop or be a child of `<Dialog.Root/>`',
	);
}
const id = resolvedModel.init('trigger');

const state = inject(STATE_KEY) ?? ref(resolvedModel.getState());

onMounted(() => resolvedModel.mount(id));
onUnmounted(() => resolvedModel.unmount(id));

const node = ref<HTMLElement | null>(null);
watchEffect(() => {
	if (node.value === null) {
		resolvedModel.unbindNode(id);
	} else {
		resolvedModel.bindNode(id, node.value);
	}
});
</script>

<template>
	<button
		ref="node"
		v-bind="{
			...resolvedModel.componentAttributes(id, state),
			...$attrs,
		}"
		@click="
			() => resolvedModel.setState((prevState) => ({...prevState, open: true}))
		"
	>
		<slot />
	</button>
</template>

// packages/dialog/svelte/lib/DialogTrigger.svelte
<script lang="ts">
	import type {DialogModel} from '@ally-ui/core-dialog';
	import {createEventForwarder} from '@ally-ui/svelte';
	import {get_current_component, onMount} from 'svelte/internal';
	import type {Readable} from 'svelte/store';
	import {getDialogContext} from './context';

	type $$Props = svelteHTML.IntrinsicElements['button'] & {
		model?: Readable<DialogModel>;
	};

	export let model: Readable<DialogModel> | undefined = undefined;
	const resolvedModel = model ?? getDialogContext();
	if (resolvedModel === undefined) {
		throw new Error(
			'<Dialog.Trigger /> must have a `model` prop or be a child of `<Dialog.Root/>`',
		);
	}
	const id = $resolvedModel.init('trigger');

	onMount(() => {
		$resolvedModel.mount(id);
		return () => {
			$resolvedModel.unmount(id);
		};
	});

	let node: HTMLElement | null = null;
	$: bindNode(node);
	function bindNode(node: HTMLElement | null) {
		if (node === null) {
			$resolvedModel.unbindNode(id);
		} else {
			$resolvedModel.bindNode(id, node);
		}
	}

	const eventForwarder = createEventForwarder(get_current_component());
</script>

<button
	bind:this={node}
	{...$resolvedModel.componentAttributes(id)}
	{...$$restProps}
	use:eventForwarder
	on:click={() =>
		$resolvedModel.setState((prevState) => ({...prevState, open: true}))}
>
	<slot />
</button>
