// packages/dialog/vue/lib/DialogPortal.vue
<script setup lang="ts">
import {inject, provide, ref} from 'vue';
import {
	DIALOG_ROOT_MODEL,
	DIALOG_ROOT_STATE,
	DIALOG_PORTAL_FORCE_MOUNT,
} from './context';

export type DialogPortalProps = {
	container?: HTMLElement | string;
	forceMount?: boolean;
};
const props = withDefaults(defineProps<DialogPortalProps>(), {
	container: 'body',
	forceMount: undefined,
});

const rootModel = inject(DIALOG_ROOT_MODEL);
if (rootModel == null) {
	throw new Error('<Dialog.Portal/> must be a child of `<Dialog.Root/>`');
}

const rootState = inject(DIALOG_ROOT_STATE) ?? ref(rootModel.state.value);

provide(DIALOG_PORTAL_FORCE_MOUNT, props.forceMount);
</script>

<template>
	<Teleport
		:to="props.container"
		:disabled="!rootState.open"
		v-if="rootState.open"
	>
		<slot />
	</Teleport>
</template>

// packages/dialog/svelte/lib/DialogPortal.svelte
<script lang="ts" context="module">
	type DialogPortalProps = {
		container?: HTMLElement | string;
		forceMount?: boolean;
	};
</script>

<script lang="ts">
	import Portal from 'svelte-portal';
	import {readable} from 'svelte/store';
	import {
		getDialogRootModel,
		getDialogRootState,
		setDialogPortalForceMount,
	} from './context';

	type $$Props = DialogPortalProps;

	const rootModel = getDialogRootModel();
	if (rootModel == null) {
		throw new Error('<Dialog.Portal/> must be a child of `<Dialog.Root/>`');
	}

	const rootState = getDialogRootState() ?? readable(rootModel.state.value);

	export let container: HTMLElement | string | undefined = undefined;
	export let forceMount: boolean | undefined = undefined;
	setDialogPortalForceMount(forceMount);
</script>

{#if $rootState.open}
	<Portal target={container}>
		<slot />
	</Portal>
{/if}
