// packages/dialog/solid/lib/DialogContent.tsx
import type {DialogModel} from '@ally-ui/core-dialog';
import {combinedRef} from '@ally-ui/solid';
import {JSX, onCleanup, onMount, Show, splitProps} from 'solid-js';
import {useDialogModelContext, useDialogStateContext} from './context';

export interface DialogContentProps extends JSX.HTMLAttributes<HTMLDivElement> {
	model?: DialogModel;
	ref?: (node: HTMLDivElement) => void;
}

export default function DialogContent(props: DialogContentProps) {
	const [local, restProps] = splitProps(props, ['model', 'ref', 'children']);
	const resolvedModel = useDialogModelContext() ?? local.model;
	if (resolvedModel === undefined) {
		throw new Error(
			'<Dialog.Content/> must have a `model` prop or be a child of `<Dialog.Root/>`',
		);
	}
	const id = resolvedModel.init('content');

	const resolvedState = useDialogStateContext() ?? resolvedModel.getState();

	onMount(() => {
		resolvedModel.mount(id);
	});
	onCleanup(() => {
		resolvedModel.unmount(id);
	});

	const bindRef = (node: HTMLElement) => {
		resolvedModel.bindNode(id, node);
	};
	onCleanup(() => {
		resolvedModel.unbindNode(id);
	});
	const ref = combinedRef(bindRef, local.ref);

	return (
		<Show when={resolvedState.open}>
			<div
				ref={ref}
				{...resolvedModel.componentAttributes(id, resolvedState)}
				{...restProps}
			>
				{local.children}
			</div>
		</Show>
	);
}

// packages/dialog/react/lib/DialogContent.tsx
import type {DialogModel} from '@ally-ui/core-dialog';
import {useMultipleRefs, useRunOnce} from '@ally-ui/react';
import React from 'react';
import {useDialogModelContext, useDialogStateContext} from './context';

export interface DialogContentProps
	extends React.DetailedHTMLProps<
		React.HTMLAttributes<HTMLDivElement>,
		HTMLDivElement
	> {
	model?: DialogModel;
}

const DialogContent = React.forwardRef<HTMLElement, DialogContentProps>(
	({model, children, ...restProps}, forwardedRef) => {
		const resolvedModel = useDialogModelContext() ?? model;
		if (resolvedModel === undefined) {
			throw new Error(
				'<Dialog.Content /> must have a `model` prop or be a child of `<Dialog.Root/>`',
			);
		}
		const id = useRunOnce(() => resolvedModel.init('content'));

		const resolvedState = useDialogStateContext() ?? resolvedModel.getState();

		React.useEffect(
			function mount() {
				resolvedModel.mount(id);
				return () => {
					resolvedModel.unmount(id);
				};
			},
			[resolvedModel],
		);

		const bindRef = React.useCallback(
			(node: HTMLElement | null) => {
				if (node === null) {
					resolvedModel.unbindNode(id);
				} else {
					resolvedModel.bindNode(id, node);
				}
			},
			[resolvedModel],
		);
		const ref = useMultipleRefs(bindRef, forwardedRef);

		return (
			<>
				{resolvedState.open && (
					<div
						ref={ref}
						{...resolvedModel.componentAttributes(id, resolvedState)}
						{...restProps}
					>
						{children}
					</div>
				)}
			</>
		);
	},
);

export default DialogContent;
