// packages/dialog/solid/lib/DialogRoot.tsx
import {
	DialogRootModel,
	type DialogRootModelOptions,
} from '@ally-ui/core-dialog';
import {createSyncedOption} from '@ally-ui/solid';
import {createEffect, ParentProps} from 'solid-js';
import {createStore} from 'solid-js/store';
import {DialogRootModelContext, DialogRootStateContext} from './context';

export interface DialogRootProps extends ParentProps, DialogRootModelOptions {
	open?: boolean;
	onOpenChange?: (open: boolean) => void;
}

export default function DialogRoot(props: DialogRootProps) {
	const id = '0';
	const rootModel = new DialogRootModel(id, {
		initialOpen: props.initialOpen,
		modal: props.modal,
	});
	const [rootState, setRootState] = createStore({...rootModel.initialState});
	rootModel.setStateOptions((prevOptions) => ({
		...prevOptions,
		requestStateUpdate: setRootState,
	}));
	createSyncedOption({
		option: () => props.open,
		onOptionChange: (open) =>
			setRootState((prevState) => ({...prevState, open})),
		internal: () => rootState.open,
		onInternalChange: props.onOpenChange,
	});
	createSyncedOption({
		option: () => props.modal,
		onOptionChange: (modal) =>
			setRootState((prevState) => ({...prevState, modal})),
	});
	createEffect(function onStateUpdate() {
		rootModel.setState({...rootState});
	});
	return (
		<DialogRootModelContext.Provider value={rootModel}>
			<DialogRootStateContext.Provider value={rootState}>
				{props.children}
			</DialogRootStateContext.Provider>
		</DialogRootModelContext.Provider>
	);
}

// packages/dialog/react/lib/DialogRoot.tsx
import {
	DialogRootModel,
	type DialogRootModelOptions,
} from '@ally-ui/core-dialog';
import {useRunOnce, useSyncedOption} from '@ally-ui/react';
import React from 'react';
import {DialogRootModelContext, DialogRootStateContext} from './context';

export interface DialogRootProps
	extends React.PropsWithChildren,
		DialogRootModelOptions {
	open?: boolean;
	onOpenChange?: (open: boolean) => void;
}

export default function DialogRoot({
	children,
	initialOpen,
	modal,
	onOpenChange,
	open,
}: DialogRootProps) {
	const id = React.useId();
	const rootModel = useRunOnce(
		() => new DialogRootModel(id, {initialOpen, modal}),
	);
	const [rootState, setRootState] = React.useState(
		() => rootModel.initialState,
	);
	useRunOnce(() => {
		rootModel.setStateOptions((prevOptions) => ({
			...prevOptions,
			requestStateUpdate: setRootState,
		}));
	});
	useSyncedOption({
		option: open,
		onOptionChange: (open) =>
			setRootState((prevState) => ({...prevState, open})),
		internal: rootState.open,
		onInternalChange: onOpenChange,
	});
	React.useEffect(
		function onStateUpdate() {
			rootModel.setState(rootState);
		},
		[rootState],
	);

	return (
		<DialogRootModelContext.Provider value={rootModel}>
			<DialogRootStateContext.Provider value={rootState}>
				{children}
			</DialogRootStateContext.Provider>
		</DialogRootModelContext.Provider>
	);
}
