// packages/dialog/solid/lib/DialogContent.solid.tsx
import {
	DialogContentModel,
	type DialogContentModelAttributes,
	type DialogContentModelOptions,
} from '@ally-ui/core-dialog';
import {
	combinedRef,
	createDelayedBindRef,
	createSyncedOption,
	Slot,
	SlottableProps,
} from '@ally-ui/solid';
import {createEffect, JSX, onCleanup, onMount, Show} from 'solid-js';
import {createStore} from 'solid-js/store';
import {useDialogRootModel, useDialogRootState} from './context';

export type DialogContentProps = SlottableProps<
	DialogContentModelAttributes,
	JSX.HTMLAttributes<HTMLDivElement>
> &
	DialogContentModelOptions;

export default function DialogContent(props: DialogContentProps) {
	const rootModel = useDialogRootModel();
	if (rootModel === undefined) {
		throw new Error('<Dialog.Content/> must be a child of `<Dialog.Root/>`');
	}
	const component = rootModel.registerComponent(
		new DialogContentModel(rootModel, {
			forceMount: props.forceMount,
			onOpenAutoFocus: props.onOpenAutoFocus,
			onCloseAutoFocus: props.onCloseAutoFocus,
			onEscapeKeyDown: props.onEscapeKeyDown,
			onInteractOutside: props.onInteractOutside,
		}),
	);
	const id = component.getId();
	const [state, setState] = createStore(component.initialState);
	component.requestStateUpdate = setState;
	// TODO #44 Reduce syncing boilerplate.
	createSyncedOption({
		option: () => props.onOpenAutoFocus,
		onOptionChange: (onOpenAutoFocus) =>
			setState((prevState) => ({...prevState, onOpenAutoFocus})),
	});
	createSyncedOption({
		option: () => props.onCloseAutoFocus,
		onOptionChange: (onCloseAutoFocus) =>
			setState((prevState) => ({...prevState, onCloseAutoFocus})),
	});
	createSyncedOption({
		option: () => props.onEscapeKeyDown,
		onOptionChange: (onEscapeKeyDown) =>
			setState((prevState) => ({...prevState, onEscapeKeyDown})),
	});
	createSyncedOption({
		option: () => props.onInteractOutside,
		onOptionChange: (onInteractOutside) =>
			setState((prevState) => ({...prevState, onInteractOutside})),
	});
	createEffect(function onStateUpdate() {
		component.setState({...state});
	});

	const rootState = useDialogRootState() ?? rootModel.state;
	const derivedState = () => component.deriveState(rootState);

	onMount(() => {
		rootModel.mountComponent(id);
	});
	onCleanup(() => {
		rootModel.unmountComponent(id);
		rootModel.deregisterComponent(id);
	});

	const bindRef = createDelayedBindRef(
		(node) => {
			if (node === null) {
				rootModel.unbindComponent(id);
			} else {
				rootModel.bindComponent(id, node);
			}
		},
		() => derivedState().show,
	);
	const ref = combinedRef(bindRef, props.ref);

	return (
		<Show when={derivedState().show}>
			<Slot
				ref={ref}
				props={props}
				attributes={component.getAttributes(rootState)}
			>
				{(renderProps) => (
					<div ref={renderProps.ref} {...renderProps.attributes()}>
						{renderProps.children}
					</div>
				)}
			</Slot>
		</Show>
	);
}

// packages/dialog/react/lib/DialogContent.react.tsx
import {
	DialogContentModel,
	type DialogContentModelAttributes,
	type DialogContentModelOptions,
} from '@ally-ui/core-dialog';
import {
	Slot,
	SlottableProps,
	useMultipleRefs,
	useRunOnce,
	useSyncedOption,
} from '@ally-ui/react';
import React from 'react';
import {
	useDialogPortalForceMount,
	useDialogRootModel,
	useDialogRootState,
} from './context';

export type DialogContentProps = SlottableProps<
	DialogContentModelAttributes,
	React.DetailedHTMLProps<React.HTMLAttributes<HTMLDivElement>, HTMLDivElement>
> &
	DialogContentModelOptions;

const DialogContent = React.forwardRef<HTMLElement, DialogContentProps>(
	(
		{
			forceMount,
			onOpenAutoFocus,
			onCloseAutoFocus,
			onEscapeKeyDown,
			onInteractOutside,
			...props
		},
		forwardedRef,
	) => {
		const rootModel = useDialogRootModel();
		if (rootModel === undefined) {
			throw new Error('<Dialog.Content/> must be a child of `<Dialog.Root/>`');
		}
		const portalForceMount = useDialogPortalForceMount();
		const component = useRunOnce(() =>
			rootModel.registerComponent(
				new DialogContentModel(rootModel, {
					forceMount: forceMount ?? portalForceMount,
					onOpenAutoFocus,
					onCloseAutoFocus,
					onEscapeKeyDown,
					onInteractOutside,
				}),
			),
		);
		const id = component.getId();

		const [state, setState] = React.useState(() => component.initialState);
		useRunOnce(() => {
			component.requestStateUpdate = setState;
		});
		// TODO #44 Reduce syncing boilerplate.
		useSyncedOption({
			option: onOpenAutoFocus,
			onOptionChange: (onOpenAutoFocus) =>
				setState((prevState) => ({...prevState, onOpenAutoFocus})),
		});
		useSyncedOption({
			option: onCloseAutoFocus,
			onOptionChange: (onCloseAutoFocus) =>
				setState((prevState) => ({...prevState, onCloseAutoFocus})),
		});
		useSyncedOption({
			option: onEscapeKeyDown,
			onOptionChange: (onEscapeKeyDown) =>
				setState((prevState) => ({...prevState, onEscapeKeyDown})),
		});
		useSyncedOption({
			option: onInteractOutside,
			onOptionChange: (onInteractOutside) =>
				setState((prevState) => ({...prevState, onInteractOutside})),
		});
		React.useEffect(
			function onStateUpdate() {
				component.setState(state);
			},
			[state],
		);

		const rootState = useDialogRootState() ?? rootModel.state;
		const derivedState = component.deriveState(rootState);

		React.useEffect(
			function mount() {
				rootModel.mountComponent(id);
				return () => {
					rootModel.unmountComponent(id);
					// rootModel.deregisterComponent(id);
				};
			},
			[rootModel],
		);

		const bindRef = React.useCallback(
			(node: HTMLElement | null) => {
				if (node === null) {
					rootModel.unbindComponent(id);
				} else {
					rootModel.bindComponent(id, node);
				}
			},
			[rootModel],
		);
		const ref = useMultipleRefs(bindRef, forwardedRef);

		return (
			<>
				{derivedState.show && (
					<Slot
						slotRef={ref}
						props={props}
						attributes={component.getAttributes(rootState)}
					>
						{({ref, children, attributes}) => (
							<div ref={ref} {...attributes}>
								{children}
							</div>
						)}
					</Slot>
				)}
			</>
		);
	},
);

export default DialogContent;
