// packages/dialog/react/lib/context.ts
import type {DialogRootModel, DialogRootModelState} from '@ally-ui/core-dialog';
import React from 'react';

export const DialogRootModelContext = React.createContext<
	DialogRootModel | undefined
>(undefined);
export function useDialogRootModel() {
	return React.useContext(DialogRootModelContext);
}

export const DialogRootStateContext = React.createContext<
	DialogRootModelState | undefined
>(undefined);
export function useDialogRootState() {
	return React.useContext(DialogRootStateContext);
}

export const DialogPortalForceMountContext = React.createContext<
	boolean | undefined
>(undefined);
export function useDialogPortalForceMount() {
	return React.useContext(DialogPortalForceMountContext);
}

// packages/dialog/solid/lib/context.ts
import type {DialogRootModel, DialogRootModelState} from '@ally-ui/core-dialog';
import {createContext, useContext} from 'solid-js';

export const DialogRootModelContext = createContext<DialogRootModel>();
export function useDialogRootModel() {
	return useContext(DialogRootModelContext);
}

export const DialogRootStateContext = createContext<DialogRootModelState>();
export function useDialogRootState() {
	return useContext(DialogRootStateContext);
}

export const DialogPortalForceMountContext = createContext<boolean | undefined>(
	undefined,
);
export function useDialogPortalForceMount() {
	return useContext(DialogPortalForceMountContext);
}
