// packages/dialog/react/lib/DialogTrigger.tsx
import type {DialogModel} from '@ally-ui/core-dialog';
import {useMultipleRefs, useRunOnce} from '@ally-ui/react';
import React from 'react';
import {useDialogModelContext, useDialogStateContext} from './context';

export interface DialogTriggerProps
	extends React.DetailedHTMLProps<
		React.ButtonHTMLAttributes<HTMLButtonElement>,
		HTMLButtonElement
	> {
	model?: DialogModel;
}

const DialogTrigger = React.forwardRef<HTMLButtonElement, DialogTriggerProps>(
	({model, children, onClick, ...restProps}, forwardedRef) => {
		const resolvedModel = useDialogModelContext() ?? model;
		if (resolvedModel === undefined) {
			throw new Error('<Dialog.Trigger/> must be a child of `<Dialog.Root/>`');
		}
		const id = useRunOnce(() => resolvedModel.init('trigger'));

		const resolvedState = useDialogStateContext() ?? resolvedModel.getState();

		React.useEffect(
			function mount() {
				resolvedModel.mount(id);
				return () => {
					resolvedModel.unmount(id);
				};
			},
			[resolvedModel],
		);

		const bindRef = React.useCallback(
			(node: HTMLElement | null) => {
				if (node === null) {
					resolvedModel.unbindNode(id);
				} else {
					resolvedModel.bindNode(id, node);
				}
			},
			[resolvedModel],
		);
		const ref = useMultipleRefs(bindRef, forwardedRef);

		const handleClick = React.useCallback<
			React.MouseEventHandler<HTMLButtonElement>
		>(
			(ev) => {
				onClick?.(ev);
				resolvedModel.open();
			},
			[resolvedModel],
		);

		return (
			<button
				ref={ref}
				{...resolvedModel.componentAttributes(id, resolvedState)}
				{...restProps}
				onClick={handleClick}
			>
				{children}
			</button>
		);
	},
);

export default DialogTrigger;

// packages/dialog/solid/lib/DialogTrigger.tsx
import type {DialogModel} from '@ally-ui/core-dialog';
import {combinedRef, forwardEvent} from '@ally-ui/solid';
import {createEffect, JSX, splitProps} from 'solid-js';
import {useDialogModelContext, useDialogStateContext} from './context';

export interface DialogTriggerProps
	extends JSX.HTMLAttributes<HTMLButtonElement> {
	model?: DialogModel;
	ref?: (node: HTMLButtonElement) => void;
}

export default function DialogTrigger(props: DialogTriggerProps) {
	const [local, restProps] = splitProps(props, ['model', 'ref', 'onClick']);
	const resolvedModel = useDialogModelContext() ?? local.model;
	if (resolvedModel === undefined) {
		throw new Error(
			'<Dialog.Trigger/> must have a `model` prop or be a child of `<Dialog.Root/>`',
		);
	}
	const id = resolvedModel.init('trigger');

	const resolvedState = useDialogStateContext() ?? resolvedModel.getState();

	createEffect(
		function mount() {
			resolvedModel.mount(id);
			return () => {
				resolvedModel.unmount(id);
			};
		},
		[resolvedModel],
	);

	const bindRef = (node: HTMLElement | null) => {
		if (node === null) {
			resolvedModel.unbindNode(id);
		} else {
			resolvedModel.bindNode(id, node);
		}
	};

	const ref = combinedRef(bindRef, local.ref);

	return (
		<button
			ref={ref}
			{...resolvedModel.componentAttributes(id, resolvedState)}
			{...restProps}
			onClick={(ev) => {
				forwardEvent(ev, local.onClick);
				resolvedModel.open();
			}}
		>
			{restProps.children}
		</button>
	);
}
