// packages/dialog/react/lib/DialogDescription.react.tsx
import {
	DialogDescriptionModel,
	type DialogDescriptionModelAttributes,
} from '@ally-ui/core-dialog';
import {
	Slot,
	SlottableProps,
	useMultipleRefs,
	useRunOnce,
} from '@ally-ui/react';
import React from 'react';
import {useDialogRootModel} from './context';

export type DialogDescriptionProps = SlottableProps<
	DialogDescriptionModelAttributes,
	React.DetailedHTMLProps<
		React.HTMLAttributes<HTMLParagraphElement>,
		HTMLParagraphElement
	>
>;

const DialogDescription = React.forwardRef<HTMLElement, DialogDescriptionProps>(
	(props, forwardedRef) => {
		const rootModel = useDialogRootModel();
		if (rootModel === undefined) {
			throw new Error(
				'<Dialog.Description/> must be a child of `<Dialog.Root/>`',
			);
		}
		const component = useRunOnce(() =>
			rootModel.registerComponent(new DialogDescriptionModel(rootModel, {})),
		);
		const id = component.getId();

		React.useEffect(
			function mount() {
				rootModel.mountComponent(id);
				return () => {
					rootModel.unmountComponent(id);
					// rootModel.deregisterComponent(id);
				};
			},
			[rootModel],
		);

		const bindRef = React.useCallback(
			(node: HTMLElement | null) => {
				if (node === null) {
					rootModel.unbindComponent(id);
				} else {
					rootModel.bindComponent(id, node);
				}
			},
			[rootModel],
		);
		const ref = useMultipleRefs(bindRef, forwardedRef);

		return (
			<Slot slotRef={ref} props={props} attributes={component.getAttributes()}>
				{({ref, attributes, children}) => (
					<p ref={ref} {...attributes}>
						{children}
					</p>
				)}
			</Slot>
		);
	},
);

export default DialogDescription;

// packages/dialog/solid/lib/DialogDescription.solid.tsx
import {
	DialogDescriptionModel,
	type DialogCloseModelAttributes,
} from '@ally-ui/core-dialog';
import {combinedRef, createBindRef, Slot, SlottableProps} from '@ally-ui/solid';
import {JSX, onCleanup, onMount} from 'solid-js';
import {useDialogRootModel} from './context';

export type DialogDescriptionProps = SlottableProps<
	DialogCloseModelAttributes,
	JSX.HTMLAttributes<HTMLParagraphElement>
>;

export default function DialogDescription(props: DialogDescriptionProps) {
	const rootModel = useDialogRootModel();
	if (rootModel === undefined) {
		throw new Error(
			'<Dialog.Description/> must be a child of `<Dialog.Root/>`',
		);
	}
	const component = rootModel.registerComponent(
		new DialogDescriptionModel(rootModel, {}),
	);
	const id = component.getId();

	onMount(() => {
		rootModel.mountComponent(id);
	});
	onCleanup(() => {
		rootModel.unmountComponent(id);
		rootModel.deregisterComponent(id);
	});

	const bindRef = createBindRef((node) => {
		if (node === null) {
			rootModel.unbindComponent(id);
		} else {
			rootModel.bindComponent(id, node);
		}
	});
	const ref = combinedRef(bindRef, props.ref);

	return (
		<Slot ref={ref} props={props} attributes={component.getAttributes()}>
			{(renderProps) => (
				<p ref={renderProps.ref} {...renderProps.attributes()}>
					{renderProps.children}
				</p>
			)}
		</Slot>
	);
}
