// packages/dialog/react/lib/DialogClose.react.tsx
import {
	DialogCloseModel,
	type DialogCloseModelAttributes,
} from '@ally-ui/core-dialog';
import {
	Slot,
	SlottableProps,
	useMultipleRefs,
	useRunOnce,
} from '@ally-ui/react';
import React from 'react';
import {useDialogRootModel} from './context';

export interface DialogCloseHandlers {
	onClick: React.MouseEventHandler;
}

export type DialogCloseProps = SlottableProps<
	DialogCloseModelAttributes & DialogCloseHandlers,
	React.DetailedHTMLProps<
		React.ButtonHTMLAttributes<HTMLButtonElement>,
		HTMLButtonElement
	>
>;

const DialogClose = React.forwardRef<HTMLButtonElement, DialogCloseProps>(
	(props, forwardedRef) => {
		const rootModel = useDialogRootModel();
		if (rootModel === undefined) {
			throw new Error('<Dialog.Close/> must be a child of `<Dialog.Root/>`');
		}
		const component = useRunOnce(() =>
			rootModel.registerComponent(new DialogCloseModel(rootModel, {})),
		);
		const id = component.getId();

		React.useEffect(
			function mount() {
				rootModel.mountComponent(id);
				return () => {
					rootModel.unmountComponent(id);
					rootModel.deregisterComponent(id);
				};
			},
			[rootModel],
		);

		const bindRef = React.useCallback(
			(node: HTMLElement | null) => {
				if (node === null) {
					rootModel.unbindComponent(id);
				} else {
					rootModel.bindComponent(id, node);
				}
			},
			[rootModel],
		);
		const ref = useMultipleRefs(bindRef, forwardedRef);

		const handleClick = React.useCallback<
			React.MouseEventHandler<HTMLButtonElement>
		>(
			(ev) => {
				if (!props.asChild) {
					props.onClick?.(ev);
				}
				component.onClick();
			},
			[rootModel],
		);

		return (
			<Slot
				slotRef={ref}
				props={props}
				attributes={{
					...component.getAttributes(),
					onClick: handleClick,
				}}
				mergeProps={(attributes, userProps) => ({
					...attributes,
					...userProps,
					onClick: (ev) => {
						userProps.onClick?.(ev);
						attributes.onClick(ev);
					},
				})}
			>
				{({ref, children, attributes}) => (
					<button ref={ref} {...attributes}>
						{children}
					</button>
				)}
			</Slot>
		);
	},
);

export default DialogClose;

// packages/dialog/solid/lib/DialogClose.solid.tsx
import {
	DialogCloseModel,
	type DialogCloseModelAttributes,
} from '@ally-ui/core-dialog';
import {
	combinedRef,
	createBindRef,
	forwardEvent,
	Slot,
	type SlottableProps,
} from '@ally-ui/solid';
import {JSX, onCleanup, onMount} from 'solid-js';
import {useDialogRootModel} from './context';

export interface DialogCloseHandlers {
	onClick: JSX.EventHandlerUnion<HTMLElement, Event>;
}

export type DialogCloseProps = SlottableProps<
	DialogCloseModelAttributes & DialogCloseHandlers,
	JSX.HTMLAttributes<HTMLButtonElement>
>;

export default function DialogClose(props: DialogCloseProps) {
	const rootModel = useDialogRootModel();
	if (rootModel === undefined) {
		throw new Error('<Dialog.Close/> must be a child of `<Dialog.Root/>`');
	}
	const component = rootModel.registerComponent(
		new DialogCloseModel(rootModel, {}),
	);
	const id = component.getId();

	onMount(() => {
		rootModel.mountComponent(id);
	});
	onCleanup(() => {
		rootModel.unmountComponent(id);
		rootModel.deregisterComponent(id);
	});

	const bindRef = createBindRef((node) => {
		if (node === null) {
			rootModel.unbindComponent(id);
		} else {
			rootModel.bindComponent(id, node);
		}
	});
	const ref = combinedRef(bindRef, props.ref);

	const handleClick: DialogCloseHandlers['onClick'] = (ev) => {
		if (!props.asChild) {
			forwardEvent(
				ev as MouseEvent & {
					currentTarget: HTMLButtonElement;
					target: Element;
				},
				props.onClick,
			);
		}
		component.onClick();
	};

	return (
		<Slot
			ref={ref}
			props={props}
			attributes={{...component.getAttributes(), onClick: handleClick}}
			mergeProps={(attributes, userProps) => ({
				...attributes,
				...userProps,
				onClick: (ev) => {
					forwardEvent(ev, userProps.onClick);
					attributes.onClick(ev);
				},
			})}
		>
			{(renderProps) => (
				<button ref={renderProps.ref} {...renderProps.attributes()}>
					{renderProps.children}
				</button>
			)}
		</Slot>
	);
}
