// packages/svelte-dialog/lib/DialogContent.svelte
<script lang="ts">
	import type {DialogModel} from '@ally-ui/core-dialog';
	import type {Readable} from 'svelte/store';

	export let model: Readable<DialogModel>;
	const id = $model.init('content');

	let node: HTMLElement | undefined;
	$: bindNode(node);
	function bindNode(node?: HTMLElement) {
		if (node === undefined) {
			$model.unbindNode(id);
		} else {
			$model.bindNode(id, node);
		}
	}
</script>

{#if $model.getState().open}
	<div bind:this={node} {...$model.submodelDOMAttributes(id)}>
		<slot />
	</div>
{/if}

// packages/react-dialog/lib/DialogContent.tsx
import {type DialogModel} from '@ally-ui/core-dialog';
import {useRunOnce} from '@ally-ui/react-utils';
import {PropsWithChildren, useCallback} from 'react';

export interface DialogContentProps extends PropsWithChildren {
	model: DialogModel;
}

export default function DialogContent({model, children}: DialogContentProps) {
	const id = useRunOnce(() => model.init('content'));

	const ref = useCallback(
		(node: HTMLElement | null) => {
			if (node === null) {
				model.unbindNode(id);
			} else {
				model.bindNode(id, node);
			}
		},
		[model],
	);

	return (
		<>
			{model.getState().open && (
				<div ref={ref} {...model.submodelDOMAttributes(id)}>
					{children}
				</div>
			)}
		</>
	);
}
